apps/portfolio/turbo.json, apps/sessions-demo/turbo.json, turbo.json
There's a race condition between `@fogo/sessions-demo#build` and `@fogo/sessions-demo#test:types` because test:types checks some types inside `.next`
=> fix: turbo race condition

programs/session-manager/src/lib.rs
By default anchor assigns an 8 byte discriminator to instructions, which is derived from the instruction name.
These 8 bytes are the first 8 bytes of the instruction payload and are used by the program to understand which task it needs to execute.
Since a frequent problem on SVM is transaction size, I prefer to set a 1 byte discriminator manually.
=> feat: shorten instruction discriminator

apps/sessions-demo/src/components/Home/use-airdrop.ts, apps/sessions-demo/src/components/Home/use-trade.ts, packages/sessions-sdk-react/package.json, packages/sessions-sdk-react/src/session-button.module.scss, packages/sessions-sdk-react/src/session-limits.module.scss, packages/sessions-sdk-react/src/session-provider.module.scss, packages/sessions-sdk-react/src/session-provider.tsx, packages/sessions-sdk-react/src/theme.scss, packages/sessions-sdk-react/src/use-token-account-data.ts, packages/sessions-sdk/package.json, pnpm-lock.yaml
This commit attempts to add some reset & font css to ensure that the widget gets a consistent style, regardless of the context of the surrounding app.  It won't be perfectly isolated, but it should do a fairly good job in most situations.
This commit also adds some code to bust the token account data cache after transactions are sent successfully.
=> fix: ensure styling is consistent and handle swr mutations

packages/sessions-sdk-react/package.json, packages/sessions-sdk-react/src/session-provider.tsx, packages/sessions-sdk-ts/package.json, packages/sessions-sdk-ts/src/index.ts
This will be necessary for apps that only read account metadata but does not perform transactions, for instance, if we have a faucet app, or an account portfolio app, etc.
In these cases, the app does not request access to any tokens, and the session init flow skips the limit setting popup
=> feat: allow sessions to be created with no permissions

packages/sessions-sdk-ts/package.json, packages/sessions-sdk-ts/src/index.ts
We only use `Wallet` as a type, usually the tsconfig `verbatimModuleSyntax` option (which we have set) catches these and ensures we add a type import, but it doesn't seem to work when importing es6 classes.
It's important to mark this as a type-only import, because it's not available in some environments, such as when bundled for the browser
=> fix: fix type-only import

packages/sessions-sdk-react/package.json, packages/sessions-sdk-ts/package.json, packages/sessions-sdk-web/package.json, pnpm-lock.yaml
This ensures that workspace dependencies get transformed to version ranges rather than using exact versions.  This is important because it ensures we can version underlying packages (e.g. `@fogo/sessions-sdk`) without also publishing all packages that depend on the underlying packages
=> fix: ensure workspace dependency versions float

Cargo.lock, apps/sessions-demo/src/components/Home/use-trade.ts, packages/sessions-sdk-rs/Cargo.toml, packages/sessions-sdk-rs/src/session/mod.rs, packages/sessions-sdk-rs/src/token/instruction.rs, packages/sessions-sdk-rs/src/token/mod.rs, programs/example/src/lib.rs
- make it easier for apps to support both session and non-session interactions at the same time
- use associated token accounts in the example as it is more conventional than arbitrary token accounts
- rename some things the flow is clearer
=> chore: improve sdk and in-code docs

.github/workflows/turbo-build.yaml, .github/workflows/turbo-test.yaml, Cargo.toml
- pin to git tag
- use locked dependencies
=> chore: fix avm ci installation

packages/sessions-sdk-react/src/session-button.module.scss
Fix the color of the logout button matching the underlying app scheme, causing the button to be nearly invisible on dark mode apps
=> fix: fix log out button text color

packages/sessions-sdk-react/src/session-provider.tsx
Until we add controls for setting the session expiration and prompts for when the session has expire, let's just set the default session duration to a long period so people don't get tripped up by this in testnet.
=> chore: extend session duration

packages/sessions-sdk-react/src/session-provider.tsx, packages/sessions-sdk-ts/src/adapter.ts, packages/sessions-sdk-ts/src/index.ts
Some use cases require adding other signers to txns, so expanding this interface to allow it to take a tx and add the session signature allows those cases to work easily.
There are some downsides to passing a tx:
- We can't set the fee payer on the partially signed tx, so users need to ensure the fee payer is set to the paymaster sponsor
- We can't set the message lifetime either
- Finally, we can't add the ALT to the tx to help compress the intent message size
These are all things the user can handle themselves, so I think it's fair to treat this as a low-level API and discourage it unless it's really needed.
=> feat: allow passing partially signed txs to `sendTransaction`

packages/sessions-sdk-ts/src/adapter.ts
Looks like the auto-fix for `unicorn/no-typeof-undefined` is a bit overzealous and actually broke this code
=> fix: fix bug in determine if we're running in browser

apps/sessions-demo/src/components/Home/demo.tsx, packages/sessions-sdk-react/src/session-button.tsx, packages/sessions-sdk-react/src/session-provider.tsx
This avoids showing the wallet popup when restoring the session, which has been very common feedback.  It makes sense to only show it when first establishing the session, where it's relevant context.
=> fix: only show wallet popup when first connecting wallet

Cargo.lock, Cargo.toml, services/paymaster/Cargo.toml, services/paymaster/src/api.rs
Fix simulation errors in the paymaster. The source of these errors is that we were simulating with the default commitment level, which is "Finalized". This means we're simulating against a relatively old chain state, which causes simulation errors if users are running multiple transactions whose effects depend on each other.
=> Use "processed" commitment level for transaction simulation

.changeset/sharp-lizards-check.md, packages/sessions-sdk-react/src/session-button.tsx, packages/sessions-sdk-react/src/session-provider.tsx
This commit adds a callback `onSessionStartInit` which can be optionally passed to trigger app behavior before starting the session initialization flow.  If passed, this callback can be an async function and can return `false` to indicate that initialization flow should not proceed.
=> feat: add a callback for before starting the session init flow

services/paymaster/src/api.rs
Let's add this.
I think the Pyron bug involved submitting partially signed transactions to the paymaster. These transactions never land.
=> feat: validate signatures

services/paymaster/src/api.rs
The default commitment is `finalized`. I think this was leading to `get_balance` returning the balance from a deeper block than the one we simulate against, causing an overestimation of the paymaster spend.
=> fix: use the same commitment for simulation and get balance

.changeset/heavy-bushes-wash.md, packages/sessions-sdk-react/package.json, packages/sessions-sdk-react/src/session-button.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
The `react-timeago` library does not ship esm correctly and it's caused issues for the typing, and some of the developers using the sdk have reported that they can't use the latest release due to issues with their environment interacting with this library.
It's a pretty simple component.  Rather than fighting with the library to get it to work correctly, I figure it's better to just home-roll this.
=> fix: replace react-timeago with a custom component

services/paymaster/src/api.rs, services/paymaster/src/config.rs, services/paymaster/src/serde.rs, tilt/configs/paymaster.toml
This PR removes simulation from the paymaster. This is in line with the shift to imperative constraints and checks and removes potentially expensive RPC calls from the paymaster logic.
=> refactor: remove simulation from paymaster

services/paymaster/src/constraint.rs, services/paymaster/src/constraint_templates.rs, tilt/configs/paymaster.toml
This PR improves the signer constraints given that signer order (besides the fee payer) is not easily derivable when there are more than 2 non-fee-paying signers.
=> fix: improve signer constraints

packages/sessions-sdk-rs/src/session/mod.rs, programs/session-manager/src/error.rs, programs/session-manager/src/lib.rs
This PR adds the functionality to close sessions to the on-chain program.
Only sessions whose expiration has passed can be closed definitively. 
This is because otherwise the intent that was used to create the session can be reused to recreate it.
=> feat: close sessions

Cargo.lock, services/paymaster/Cargo.toml, services/paymaster/src/constraint.rs
This PR adds an option for bytes to the `PrimitiveDataType` and `PrimitiveDataValue` types. This allows apps to more easily specify discriminators and other byte strings in their constraints.
=> feat: add bytes primitive data to paymaster

services/paymaster/src/constraint.rs, tilt/configs/paymaster.toml
Previously, Compute Budget instructions needed to be specified in v1 transaction variations. However, given the `max_gas_spend` check, this is unnecessary, and apps do not need to specify allowing Compute Budget instructions.
In addition to the `SetComputeUnitLimit` and `SetComputeUnitPrice` instructions, there are also `RequestHeapFrame` and `SetLoadedAccountsDataSizeLimit` instructions (and a deprecated `RequestUnits` instruction). These do not add to the gas cost, and they are not commonly used. Preventing use of these instructions does not appear to be critical at this time; if apps request, we can filter to only permit `SetComputeUnitLimit` and `SetComputeUnitPrice` instructions arbitrarily.
=> Fix: remove implicit compute budget

services/paymaster/src/constraint.rs
This PR fixes a bug in the include account constraints. Previously, the include account constraints were being checked as if they were AND gated. They should be checked as OR gated constraints (just one needs to be satisfied).
=> Fix: include account constraint

packages/sessions-sdk-ts/src/adapter.ts, services/paymaster/src/api.rs, services/paymaster/src/metrics.rs, services/paymaster/src/rpc.rs
This PR deprecates the `confirm` flag in the `sponsor_and_send` query. Eventually we should disable the argument altogether, after users have all upgraded to the next version of the SDK.
=> refactor: paymaster deprecate confirm option

services/paymaster/README.md, services/paymaster/src/main.rs
This PR checks for an OTLP endpoint env var to which to send spans.
=> fix: configure otlp endpoint w env var

services/paymaster/src/api.rs, services/paymaster/src/config.rs
This PR adds templates to the constraints in the paymaster config during the initial loading. This is the best implementation bc it alleviates the developer from having to manually add these in later. 
There aren't really any expected use cases where someone would want to exclude the templates from the constraints, although we could add that functionality later via an argument in the load function if needed.
=> fix: add templates to constraints during loading

Cargo.lock, services/paymaster/Cargo.toml, services/paymaster/src/api.rs, services/paymaster/src/bin/tx_validator.rs, services/paymaster/src/constraint.rs, services/paymaster/src/rpc.rs
This PR transitions to using a nonblocking RPC client. This allows for concurrent RPC calls and speeds up the transaction validator CLI tool. It also introduces basic rate limiting to accommodate concurrent requests.
In the future, we may wish to attempt retries on RPC calls, but we leave that for another PR.
=> fix: paymaster async rpc client

services/paymaster/src/config.rs, services/paymaster/src/constraint_templates.rs
This PR makes the `max_gas_spend` for the template constraints an argument rather than hardcoding it to a constant. This value can be configured in the future.
=> fix: generalize paymastter template gas spend
